# config.py

from PyQt5.QtCore import Qt

# Display
SCENE_EXTRA_GRASS = 4
LINE_WIDTH = 0.25

# Zones
GOAL_DEPTH = 2.44
GOAL_WIDTH = 7.32
PENALTY_AREA_LENGTH = 16.5
PENALTY_AREA_WIDTH = 40.3
GOAL_AREA_LENGTH = 5.5
GOAL_AREA_WIDTH = 18.32
CENTER_CIRCLE_RADIUS = 9.15
POINT_RADIUS = 0.5
PENALTY_SPOT_DIST = 11

# Offside

OFFSIDE_LINE_WIDTH = 0.5


# Player and ball
PLAYER_OUTER_RADIUS = 1.6
PLAYER_INNER_RADIUS = 1.2
PLAYER_ARROW_THICKNESS = 0.45
PLAYER_CHEVRON_SIZE = 1.0
PLAYER_ROTATION_OFFSET_DEG = 270
PLAYER_ROTATION_DEFAULT_DEG = 90  # Pour regarder vers le haut
PLAYER_CHEVRON_ANGLE_DEG = 150
BALL_RADIUS = 0.7
VELOCITY_ARROW_SCALE = 1
BALL_COLOR = "orange"




# Annotation_tools constants
ANNOTATION_ARROW_HEAD_LENGTH = 2
ANNOTATION_ARROW_HEAD_ANGLE = 30  # in degrees
ANNOTATION_ARROW_BASE_WIDTH_VALUE = 1
ANNOTATION_ARROW_SCALE_RANGE = (ANNOTATION_ARROW_BASE_WIDTH_VALUE, ANNOTATION_ARROW_BASE_WIDTH_VALUE * 10)


# ---- Timeline and UI ----
MAX_TIMELINE_WIDTH = 600
MIN_TIMELINE_WIDTH = 400
EXTRA_TIMELINE_PADDING = 60
TIMELINE_SLIDER_HEIGHT = 24    # Hauteur totale du widget slider
TIMELINE_GROOVE_HEIGHT = TIMELINE_SLIDER_HEIGHT - TIMELINE_SLIDER_HEIGHT//3     # Epaisseur de la barre (très fin)
TIMELINE_HANDLE_WIDTH = TIMELINE_GROOVE_HEIGHT // 2      # Largeur du curseur (horizontalement)
TIMELINE_HANDLE_HEIGHT = TIMELINE_GROOVE_HEIGHT + TIMELINE_GROOVE_HEIGHT//2     # Epaisseur du curseur (verticalement, donc un rectangle "épais")
NAV_BUTTON_WIDTH = 35
NAV_BUTTON_HEIGHT = 30

# time
FPS = 25               # Fréquence d’échantillonnage (frames per second)
LENGTH_FIRST_HALF = 45 # Minutes
LENGTH_SECOND_HALF = 45
LENGTH_OVERTIME_HALF = 15
LENGTH_FULL_TIME = LENGTH_FIRST_HALF + LENGTH_SECOND_HALF
LENGTH_EXTRA_TIME = 2 * LENGTH_OVERTIME_HALF



# Players and ball trajectories
TRAJECTORY_PLAYER_LINE_WIDTH = 0.3      # Traits très fins pour joueurs
TRAJECTORY_BALL_LINE_WIDTH = 0.5        # Traits fins pour balle
TRAJECTORY_STYLE = Qt.DotLine           # Pointillés
TRAJECTORY_SAMPLE_RATE = 5              
TRAJECTORY_PLAYER_MIN_OPACITY = 1
TRAJECTORY_BALL_MIN_OPACITY = 0.95
