# config.py

# Display
SCENE_EXTRA_GRASS = 4
LINE_WIDTH = 0.25

# Zones
GOAL_DEPTH = 2.44
GOAL_WIDTH = 7.32
PENALTY_AREA_LENGTH = 16.5
PENALTY_AREA_WIDTH = 40.3
GOAL_AREA_LENGTH = 5.5
GOAL_AREA_WIDTH = 18.32
CENTER_CIRCLE_RADIUS = 9.15
POINT_RADIUS = 0.5
PENALTY_SPOT_DIST = 11

# Offside

OFFSIDE_LINE_WIDTH = 0.5


# Player and ball
PLAYER_OUTER_RADIUS = 1.6
PLAYER_INNER_RADIUS = 1.2
PLAYER_ARROW_THICKNESS = 0.45
PLAYER_CHEVRON_SIZE = 1.0
PLAYER_ROTATION_OFFSET_DEG = 270
PLAYER_ROTATION_DEFAULT_DEG = 90  # Pour regarder vers le haut
PLAYER_CHEVRON_ANGLE_DEG = 150
BALL_RADIUS = 0.7
VELOCITY_ARROW_SCALE = 1




# Annotation_tools constants
ANNOTATION_ARROW_HEAD_LENGTH = 2
ANNOTATION_ARROW_HEAD_ANGLE = 30  # in degrees
ANNOTATION_ARROW_BASE_WIDTH_VALUE = 1
ANNOTATION_ARROW_SCALE_RANGE = (ANNOTATION_ARROW_BASE_WIDTH_VALUE, ANNOTATION_ARROW_BASE_WIDTH_VALUE * 10)


# time
FPS = 25               # Fréquence d’échantillonnage (frames per second)
LENGTH_FIRST_HALF = 45 # Minutes
LENGTH_SECOND_HALF = 45
LENGTH_OVERTIME_HALF = 15
LENGTH_FULL_TIME = LENGTH_FIRST_HALF + LENGTH_SECOND_HALF
LENGTH_EXTRA_TIME = 2 * LENGTH_OVERTIME_HALF

