# config.py

from PyQt5.QtCore import Qt
import os

# --- CONFIGURATION: Always use relative paths ---
CODE_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(CODE_DIR)
SVG_DIR = os.path.join(PROJECT_ROOT, "svgs/")
DATA_PATH = os.path.join(PROJECT_ROOT, "data/")

MATCH_ID = "J03WN1"
FILE_NAME_POS = f"DFL_04_03_positions_raw_observed_DFL-COM-000001_DFL-MAT-{MATCH_ID}.xml"
FILE_NAME_INFOS = f"DFL_02_01_matchinformation_DFL-COM-000001_DFL-MAT-{MATCH_ID}.xml"
FILE_NAME_EVENTS = f"DFL_03_02_events_raw_DFL-COM-000001_DFL-MAT-{MATCH_ID}.xml"

# Panel size
LEFT_PANEL_SIZE = 1200  


# Display
SCENE_EXTRA_GRASS = 48
LINE_WIDTH = 0.25

# Zones
GOAL_DEPTH = 2.44
GOAL_WIDTH = 7.32
PENALTY_AREA_LENGTH = 16.5
PENALTY_AREA_WIDTH = 40.3
GOAL_AREA_LENGTH = 5.5
GOAL_AREA_WIDTH = 18.32
CENTER_CIRCLE_RADIUS = 9.15
POINT_RADIUS = 0.5
PENALTY_SPOT_DIST = 11

# Offside

OFFSIDE_LINE_WIDTH = 0.5


# Player and ball
PLAYER_OUTER_RADIUS = 1.6
PLAYER_INNER_RADIUS = 1.2
PLAYER_ARROW_THICKNESS = 0.45
PLAYER_CHEVRON_SIZE = 1.0
PLAYER_ROTATION_OFFSET_DEG = 270
PLAYER_ROTATION_DEFAULT_DEG = 90  # Pour regarder vers le haut
PLAYER_CHEVRON_ANGLE_DEG = 150
BALL_RADIUS = 0.7
VELOCITY_ARROW_SCALE = 1
BALL_COLOR = "orange"




# Annotation_tools constants
ANNOTATION_ARROW_HEAD_LENGTH = 4
ANNOTATION_ARROW_HEAD_ANGLE = 30  # in degrees
ANNOTATION_ARROW_BASE_WIDTH_VALUE = 1
ANNOTATION_ARROW_SCALE_RANGE = (ANNOTATION_ARROW_BASE_WIDTH_VALUE, ANNOTATION_ARROW_BASE_WIDTH_VALUE * 10)


# ---- Timeline and UI ----
MAX_TIMELINE_WIDTH = 550
MIN_TIMELINE_WIDTH = 350
EXTRA_TIMELINE_PADDING = 60
TIMELINE_SLIDER_HEIGHT = 24    # Hauteur totale du widget slider
TIMELINE_GROOVE_HEIGHT = TIMELINE_SLIDER_HEIGHT - TIMELINE_SLIDER_HEIGHT//3     # Epaisseur de la barre (très fin)
TIMELINE_HANDLE_WIDTH = TIMELINE_GROOVE_HEIGHT // 2      # Largeur du curseur (horizontalement)
TIMELINE_HANDLE_HEIGHT = TIMELINE_GROOVE_HEIGHT + TIMELINE_GROOVE_HEIGHT//2     # Epaisseur du curseur (verticalement, donc un rectangle "épais")
NAV_BUTTON_WIDTH = 35
NAV_BUTTON_HEIGHT = 30

# time
FPS = 25               # Fréquence d’échantillonnage (frames per second)
LENGTH_FIRST_HALF = 45 # Minutes
LENGTH_SECOND_HALF = 45
LENGTH_OVERTIME_HALF = 15
LENGTH_FULL_TIME = LENGTH_FIRST_HALF + LENGTH_SECOND_HALF
LENGTH_EXTRA_TIME = 2 * LENGTH_OVERTIME_HALF



# Players and ball trajectories
TRAJECTORY_PLAYER_LINE_WIDTH = 0.3      # Traits très fins pour joueurs
TRAJECTORY_BALL_LINE_WIDTH = 0.5        # Traits fins pour balle
TRAJECTORY_STYLE = Qt.DotLine           # Pointillés
TRAJECTORY_SAMPLE_RATE = 5              

# Tactical simulation
TACTICAL_ARROW_DETECTION_RADIUS = PLAYER_OUTER_RADIUS  # Distance max pour associer flèche-joueur
